name: Sample CI Pipeline / Workflow

on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup Nodejs"
              uses: actions/setup-node@v6
              with:
                node-version: "21" #setup nodejs in runner machine
                
            - name: "Check Node Version"
              run: node --version

            - name: "Clone the Repo"
              uses: actions/checkout@v6

            - name: "Install Dependency"
              run: npm install

            - name: "List Directories"
              run: ls

            - name: "Run Lint"
              run: npm run lint

            - name: "Run Tests"
              run: npm test
            
            - name: "Run Build"
              run: npm run build

            - name: "Upload Product-ready build files"
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: dist